stockbrokerage/urls.py
from django.contrib import admin
from django.urls import path
from stockapp import views


urlpatterns = [
    path('admin/', admin.site.urls),

    #HOME
    path('', views.home, name="home"),

    #AUTH
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    #PORTFOLIOS
    path('createportfolio/', views.createportfolio, name='createportfolio'),
    path('myportfolios/', views.myportfolios, name='myportfolios'),
    path('viewportfolio/<int:portfolio_pk>', views.viewportfolio, name='viewportfolio'),
    path('editportfolio/<int:portfolio_pk>', views.editportfolio, name='editportfolio'),
    path('portfolio/<int:portfolio_pk>/delete', views.deleteportfolio, name='deleteportfolio'),
    path('powerbitest/', views.powerbitest, name='powerbitest'),
    path('hannah/', views.hannah, name='hannah'),
    
    #STOCKS
    path('stock/<str:stock_ticker>', views.stockpage, name='stockpage'),
]

stockapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField

# Create your models here.
class Stock(models.Model):
	ticker = models.CharField(max_length=6, primary_key=True) 
	company = models.CharField(max_length=100)
	
	def __str__(self):
		return self.ticker


class Portfolio(models.Model):
	title = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	value = MoneyField(max_digits=19, decimal_places=2, default_currency='USD')
	cash = MoneyField(max_digits=19, decimal_places=2, default_currency='USD')
	portfolio_return = models.FloatField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class Transaction(models.Model):
	ticker = models.CharField(max_length=6)
	name = models.CharField(max_length=120)
	price = models.FloatField()
	quantity = models.IntegerField(validators=[MinValueValidator(1)])
	shares_remaining = models.IntegerField(default=0, validators=[MinValueValidator(0)])
	Buy = 'Buy'
	Sell = 'Sell'
	transaction_type = models.CharField(max_length=4, choices=[(Buy,'Buy'),(Sell,'Sell')])
	buyvalue = models.FloatField(default=0)
	sellvalue = models.FloatField(default=0)
	date = models.DateTimeField(auto_now_add=True)
	portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)


	def __str__(self):
		return f"{self.portfolio} - {self.transaction_type} {self.ticker}"

class Holding(models.Model):
	ticker = models.CharField(max_length=6)
	name = models.CharField(max_length=120)
	avg_price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
	shares = models.IntegerField(validators=[MinValueValidator(0)])
	portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)


class TransactionTwo(models.Model):
	ticker = models.CharField(max_length=6)
	name = models.CharField(max_length=120)
	price = models.FloatField()
	quantity = models.IntegerField(validators=[MinValueValidator(1)])
	Buy = 'Buy'
	Sell = 'Sell'
	transaction_type = models.CharField(max_length=4, choices=[(Buy,'Buy'),(Sell,'Sell')])
	date = models.DateTimeField(auto_now_add=True)

stockapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Portfolio, Transaction, Holding

class CreateUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class CreatePortfolioForm(ModelForm):
	class Meta:
		model = Portfolio
		fields = ['title', 'value']

class EditPortfolioForm(ModelForm):
	class Meta:
		model = Portfolio
		fields = ['title']

class BuyForm(ModelForm):
	class Meta:
		model = Holding
		fields = ['shares','portfolio']

class SellForm(ModelForm):
	class Meta:
		model = Holding
		fields = ['ticker','shares']

stockapp/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.db import IntegrityError
from django.utils import timezone
from .forms import CreateUserForm, CreatePortfolioForm, BuyForm, SellForm, EditPortfolioForm
from .models import Stock, Portfolio, Transaction, Holding
from django.db.models import Sum, Avg, F, FloatField
from decimal import Decimal
from newsapi import NewsApiClient
import plotly.express as px
import plotly.graph_objects as go
import datetime
import yfinance as yf



# Create your views here.
def home(request):
	ticker = request.GET.get('stock_ticker')
	if ticker != '' and ticker is not None:
		return redirect('stockpage', ticker)
	else:
		#NEWS FEED
		today = datetime.date.today()
		enddate = today - datetime.timedelta(days=0)
		newsapi = NewsApiClient(api_key='3022ab97a59645feb6e11dca8cb54c4a')
		get_articles = newsapi.get_everything(q='stock market',sources='the-wall-street-journal,bloomberg',domains='wsj.com,bloomberg.com',from_param=today.strftime("%Y-%m-%d"),to=enddate.strftime("%Y-%m-%d"),language='en',sort_by='relevancy',page_size=6)
		articles = get_articles['articles']
		i = 0
		articles_list = []
		while i < len(articles):
			source = (articles[i]['source']['name'])
			author = (articles[i]['author'])
			title = (articles[i]['title'])
			content = (articles[i]['content'][:180]+"...")
			date = (articles[i]['publishedAt'][:10])
			url = (articles[i]['url'])
			articles_list.append({"source":source, "author":author, "title":title, "content":content, "date":date, "url":url})
			i += 1

		#LEADERBOARD
		portfolios = Portfolio.objects.all().order_by('-portfolio_return')[:10]

		#MARKET SUMMARY
		indexes = [{"Ticker":"DOW"}, {"Ticker":"S&P 500"}, {"Ticker":"NASDAQ"}]
		tickers = ["^DJI", "^GSPC", "QQQ"]
		loop = 0
		for i in tickers:
			info = yf.Ticker(i).info
			indexes[loop]['change'] = ((info['ask']-info['regularMarketPreviousClose'])/info['regularMarketOpen'])*100
			indexes[loop]['ask'] = info['ask']
			loop += 1
		print(indexes)
		return render(request, 'stockapp/home.html', {'portfolios':portfolios,'articles':articles_list, 'indexes':indexes})

def signupuser(request):
	if request.method == "GET":
		return render(request, 'stockapp/signupuser.html', {'form':CreateUserForm()})
	else:
		if request.POST['password1'] == request.POST['password2']:
			try:
				if User.objects.filter(email=request.POST['email']).exists():
					return render(request, 'stockapp/signupuser.html', {'form':CreateUserForm(), 'error':'Email provided is already associated with an account.'})
				else:
					user = User.objects.create_user(username=request.POST['username'], email=request.POST['email'], password=request.POST['password1']) 
					user.save()
					login(request, user)
					messages.success(request, "User created successfully")
					return redirect('myportfolios')
			except IntegrityError: 
				return render(request, 'stockapp/signupuser.html', {'form':CreateUserForm(), 'error':'Username has already been taken.'})
		else:
			return render(request, 'stockapp/signupuser.html', {'form':CreateUserForm(), 'error':'Passwords did not match.'})

def loginuser(request):
	if request.method == "GET":
		return render(request, 'stockapp/loginuser.html', {'form':AuthenticationForm()})
	else:
		user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
		if user is None:
			return render(request, 'stockapp/loginuser.html', {'form':AuthenticationForm(), 'error':"Username and password did not match."})
		else:
			login(request, user)
			return redirect('myportfolios')

def logoutuser(request):
	if request.method == "POST":
		logout(request)
		return redirect('home')

def createportfolio(request):
	if request.method == "GET":
		ticker = request.GET.get('stock_ticker')
		if ticker != '' and ticker is not None:
			return redirect('stockpage', ticker)
		return render(request, 'stockapp/createportfolio.html', {'form':CreatePortfolioForm()})
	else:
		try:
			form = CreatePortfolioForm(request.POST)
			form.value = [Decimal(form['value'].value()[0]),'USD']
			newportfolio = form.save(commit=False)
			newportfolio.cash = newportfolio.value
			newportfolio.user = request.user
			newportfolio.portfolio_return = 0
			newportfolio.save()
			return redirect('home')
		except ValueError:
			return render(request, 'stockapp/createportfolio.html', {'form':CreatePortfolioForm(), 'error': 'Bad data passed in, try again.'})

def myportfolios(request):
	portfolios = Portfolio.objects.filter(user=request.user)
	ticker = request.GET.get('stock_ticker')
	if ticker != '' and ticker is not None:
		return redirect('stockpage', ticker)
	return render(request, 'stockapp/myportfolios.html', {'portfolios':portfolios})

def editportfolio(request, portfolio_pk):
	portfolio = get_object_or_404(Portfolio, pk=portfolio_pk, user=request.user)
	if request.method == "GET":
		form = EditPortfolioForm(instance=portfolio)
		return render(request, 'stockapp/editportfolio.html', {'portfolio':portfolio, 'form':form})
	else:
		try:
			form = EditPortfolioForm(request.POST, instance=portfolio)
			form.save()
			return redirect('myportfolios')
		except ValueError:
			return render(request, 'stockapp/editportfolio.html', {'portfolio':portfolio, 'form':form,'error': 'Bad data passed in, try again.'})

def deleteportfolio(request, portfolio_pk):
	portfolio = get_object_or_404(Portfolio, pk=portfolio_pk, user=request.user)
	if request.method == "POST":
		portfolio.delete()
		return redirect('myportfolios')


import yfinance as yf

def viewportfolio(request, portfolio_pk):
	portfolio_owner = Portfolio.objects.get(pk=portfolio_pk).user
	print(portfolio_owner)
	if request.method == "GET":
		ticker = request.GET.get('stock_ticker')
		if ticker != '' and ticker is not None:
			return redirect('stockpage', ticker)
		if Holding.objects.filter(portfolio=portfolio_pk):
			portfolio = list(Portfolio.objects.filter(id=portfolio_pk).values())
			qs = Holding.objects.filter(portfolio=portfolio_pk).order_by('ticker').values()
			list_qs = list(qs)
			tickers = list(qs.values('ticker'))
			l = [d['ticker'] for d in tickers]
			num = 0
			portfolio_value = []
			for ticker in l:
				d = list_qs[num]
				i = yf.Ticker(ticker)
				ask = i.info['ask']
				portfolio_value.append(d.get('shares')*ask)
				d['currentprice'] = ask
				d['return'] = ((d['currentprice']-float(d['avg_price']))/float(d['avg_price']))*100
				list_qs[num] = d
				num += 1
			portfolio_value.append(float(Portfolio.objects.values_list('cash', flat=True).get(id=portfolio_pk)))
			portfolio[0]['current_value'] = sum(portfolio_value)
			portfolio[0]['return'] = ((portfolio[0]['current_value']-float(portfolio[0]['value']))/float(portfolio[0]['value']))*100
			portfolio_object = Portfolio.objects.filter(id=portfolio_pk)
			portfolio_object.update(portfolio_return=portfolio[0]['return'])
			return render(request, 'stockapp/viewportfolio.html', {'portfolio':portfolio, 'holdings':list_qs, 'owner':portfolio_owner, 'form':SellForm()})
		else:
			ticker = request.GET.get('stock_ticker')
			if ticker != '' and ticker is not None:
				return redirect('stockpage', ticker)
			portfolio = list(Portfolio.objects.filter(id=portfolio_pk).values())
			portfolio[0]['return'] = ((float(portfolio[0]['cash'])-float(portfolio[0]['value']))/float(portfolio[0]['value']))*100
			portfolio_object = Portfolio.objects.filter(id=portfolio_pk)
			portfolio_object.update(portfolio_return=portfolio[0]['return'])
			return render(request, 'stockapp/viewportfolio.html', {'portfolio':portfolio})
	else:
		form = SellForm(request.POST)
		stock = yf.Ticker(form['ticker'].value())
		info = stock.info
		price = info['ask']
		transaction_value = int(form['shares'].value())*price
		holding = Holding.objects.filter(portfolio=portfolio_pk, ticker=form['ticker'].value())
		current_shares = holding.values_list('shares', flat=True)[0]
		shares_sold = int(form['shares'].value())
		portfolio = Portfolio.objects.filter(id=portfolio_pk)
		portfolio_cash = int(portfolio.values_list('cash', flat=True)[0])
		if current_shares-shares_sold == 0:
			portfolio.update(cash=portfolio_cash+transaction_value)
			holding.delete()
		else:
			portfolio.update(cash=portfolio_cash+transaction_value)
			holding.update(shares=current_shares-shares_sold)
		messages.success(request, "Sale processed successfully")
		return redirect('viewportfolio', portfolio_pk)

def stockpage(request, stock_ticker):
	ticker = request.GET.get('stock_ticker')
	if ticker != '' and ticker is not None:
		return redirect('stockpage', ticker)
	#Load stock page - get specific portfolios for buy form, pull stock info/historical data from yahoo finance
	try: 
		if request.user.is_authenticated:
			if request.method == "GET":
				#User's portfolios for buy form
				portfolios = Portfolio.objects.filter(user=request.user)
				#Yahoo Finance info for stock
				stock = yf.Ticker(stock_ticker)
				info = stock.info
				#Historical Data for Chart
				df = stock.history(period="1y", interval="1wk").dropna()
				labels = [x[:-9] for x in list(map(str, df.index.tolist()))]
				print(labels)
				data = [round(num, 2) for num in df['Close'].tolist()]
				print(data)
				return render(request, 'stockapp/stockpage.html', {'info':info, 'labels':labels,'data':data, 'portfolios':portfolios, 'form':BuyForm()})
			else:
				try:
					stock = yf.Ticker(stock_ticker)
					info = stock.info
					price = info['ask']
					ticker = info['symbol']
					name = info['shortName']
					form = BuyForm(request.POST)
					transaction_portfolio_cash = float(Portfolio.objects.filter(pk=form['portfolio'].value()).values_list('cash', flat=True)[0])
					transaction_value = int(form['shares'].value())*price

stockapp/templates/stockapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- REQUIRED META TAGS -- >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- BOOTSTRAP CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- STYLESHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'stockapp/css/style.css' %}">

    <!-- JAVASCRIPT -->
    <script src="{% static 'stockapp/js/main.js' %}" defer></script>

    <title>STOCKAPP</title>

  </head>
  <body>
	<nav class="navbar navbar-expand-md navbar-custom">
	<div class="container">
		{% if user.is_authenticated %}
	    <a class="navbar-brand" href="{% url 'home' %}">{{ user.username }}</a>
	    {% else %}
	    <a class="navbar-brand" href="{% url 'home' %}">Stock App</a>
	    {% endif %}
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	    	<ul class="navbar-nav ml-auto">
	            {% if user.is_authenticated %}
	                <li class="nav-item">
	                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
	                    <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
	                        {% csrf_token %}
	                        <button id="signOutBtn" type="submit">Logout</button>
	                    </form>
	                </li>
	                <li>
	                	<a class="nav-link" href="{% url 'myportfolios' %}">Portfolios</a>
	                </li>
	                <li>
	                	<a class="nav-link" href="{% url 'createportfolio' %}">Create Portfolio</a>
	                </li>
	            {% else %}
	                <li class="nav-item">
	                    <a class="nav-link" href="{% url 'signupuser' %}">Sign Up</a>
	                </li>
	                <li class="nav-item">
	                    <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
	                </li>
	            {% endif %}
	        </ul>
			<form class="d-flex" action="" method="GET">
				<input class="form-control me-2" id="stock_ticker" name="stock_ticker" type="search" placeholder="Search ticker..." aria-label="Search">
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>		
	    </div>
	</div>
	</nav>

	<br>
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}

		<!-- jQuery first, then Popper.js, Bootstrap Table then Bootstrap JS -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	
	<div class="container">
		{% block content %}{% endblock %}
	</div>
	
	<div class="footer">
		<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="../../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
	</div>

  </body>
</html>

stockapp/templates/stockapp/createportfolio.html
{% extends 'stockapp/base.html' %}

{% block content %}

	<div class="page-name">
		<h1>Create Portfolio</h1>
	</div>

	{% if error %}
		<div class="error alert alert-danger" role="alert">
	    	{{ error }}
		</div>
	{% endif %}

	<form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" name="title" class="form-control" id="id_title" required>
        </div>
        <div class="form-group">
            <label for="id_value_0">Portfolio Starting Value</label>
            <input type="number" name="value_0" class="form-control" id="id_value_0" step="10000.0" min="0" required><input type="hidden" name="value_1" required id="id_value_1" value="USD">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>


{% endblock %}

stockapp/templates/stockapp/hannah.html
{% extends 'stockapp/base.html' %}

{% block content %}

<h1>HANNAH!!!</h1>

<ul>
	<li>poop</li>
	<li>pee</li>
</ul>

{% if graph %}
{{ graph|safe }}
{% else %}
<p>No graph was provided.</p>
{% endif %}

{% endblock %}

stockapp/templates/stockapp/stockpage.html
{% extends 'stockapp/base.html' %}

{% block content %}

{% load dollarformat %}

      <div class="card">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ info.longName }} : {{ info.symbol }}</h4>
        </div>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Headquaters: {{ info.city }}, {% if info.state %} {{ info.state }},{% endif %} {{ info.country }}</li>
            <li>Website: <a href="{{ info.website }}">{{ info.website }}</a></li>
            <li>Sector: {{ info.sector }}</li>
            <li>Industry: {{ info.industry }}</li>
            <li>Price: {{ info.ask|dollar_format }}</li>
            <li>
                {% if info.dividendRate %}
                Dividend: ${{ info.dividendRate|floatformat:2 }}
                {% else %}
                Dividend N/A
                {% endif %}
             </li>
          {% if user.is_authenticated %}
          </ul>
          <form method="POST">
            {% csrf_token %}
            <label class="sr-only" for="id_shares">Quantity:</label>
            <input type="number" name="shares" required id="id_shares" min="1">
            <label class="sr-only" for="id_portfolio">Portfolio:</label>
              <select name="portfolio" required id="id_portfolio">
                {% for portfolio in portfolios %}
                <option value="{{ portfolio.id }}">{{ portfolio.title }} - {{ portfolio.cash }}</option>
                {% endfor %}
              </select>
            <button type="submit" class="btn btn-primary">Buy</button>
          </form>
          {% else %}
              <li><a href="{% url 'loginuser' %}">Login</a> or <a href="{% url 'signupuser' %}">Signup</a> to pruchase this stock</li>
          </ul>
          {% endif %}
      </div>
      <div id="chart">
        <canvas id="line-chart"></canvas>
      
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <script>
        var config = {
          type: 'line',
          data: {
            datasets: [{
              data: {{ data|safe }},
              backgroundColor: [
                '#DFDAC4'
              ],
              label: '{{ info.symbol }}'
            }],
            labels: {{ labels|safe }}
          },
          options: {
            responsive: true
          },
          options: {
            title: {
                display: true,
                text: '{{ info.shortName }} 1 Year Performance',
                fontColor: '#DFDAC4',
                position: 'top'
            },
            legend: {
              display: false
            }
          }
        };

        window.onload = function() {
          var ctx = document.getElementById('line-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };

      </script>
    </div>

  {% if error %}
    <div class="error alert alert-danger" role="alert">
        {{ error }}
    </div>
  {% endif %}

	
{% endblock %}

stockapp/templates/stockapp/viewportfolio.html
{% extends 'stockapp/base.html' %}

{% block content %}

	{% load dollarformat %}
	
	{% if holdings %}

		{% for port in portfolio %}

		<center><h1>{{ port.title }}</h1>

		Created on {{ port.created }}, funded with {{ port.value|dollar_format }}</center>
		<hr>
	<center>
		<div class="row">
        	<div class="col-md-4">
          		<div class="card shadow-sm">
					<div class="card">
						<div class="card-header">
							Buying Power
						</div>
						<div class="card-body">
							<h2>{{ port.cash|dollar_format }}</h2>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
          		<div class="card shadow-sm">
					<div class="card">
						<div class="card-header">
							Current Value
						</div>
						<div class="card-body">
							<h2>{{ port.current_value|dollar_format }}</h2>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
          		<div class="card shadow-sm">
					<div class="card">
						<div class="card-header">
							Portfolio Return
						</div>
						<div class="card-body">
							<h2>{{ port.return|floatformat:2 }}%</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</center>

		{% endfor %}
	<hr>

		<div class="table-responsive">
			<table class="table table-bordered table-hover table-dark">
			    <thead>
			    	<tr>
				        <th scope="col">Ticker</th>
				        <th scope="col">Shares</th>
				        <th scope="col">Average Price</th>
				        <th scop="col">Current Price</th>
				        <th scop="col">Return (%)</th>
				        {% if request.user == owner %}
					        <th scop="col">Quantity</th>
					        <th scop="col">Action</th>
					    {% endif %}
			    	</tr>
			    </thead>
			    <tbody>
			    {% for holding in holdings %}
					<tr>
						<form method="POST">
							{% csrf_token %}
							<td>
								<input type="text" name="ticker" maxlength="6" required id="id_ticker" value="{{ holding.ticker }}" readonly>
							</td>
							<td>{{ holding.shares }}</td>
							<td>{{ holding.avg_price|dollar_format }}</td>

							

							{% if holding.avg_price < holding.currentprice %}
							<td class="table-success">{{ holding.currentprice|dollar_format }}</td>
							{% elif holding.avg_price == holding.currentprice %}
							<td class="table-secondary">{{ holding.currentprice|dollar_format }}</td>
							{% else %}
							<td class="table-danger">{{ holding.currentprice|dollar_format }}</td>
							{% endif %}
							<td>{{ holding.return|floatformat:2 }}%</td>
							{% if request.user == owner %}
								<td>
									<input type="number" name="shares" required id="id_shares" min="1" max="{{ holding.shares }}">
								</td>
								<td>
									<button type="submit" class="btn btn-warning">Sell</button>
								</td>
							{% endif %}
						</form>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	
	{% else %}

		{% for port in portfolio %}

		<h1>{{ port.title }}</h1>

		<h2>Starting Value: {{ port.value|dollar_format }}</h2>

		<h2>Buying Power: {{ port.cash|dollar_format }}</h2>

		<h2>Portfolio Return: {{ port.return|floatformat:2 }}%</h2>

		{% endfor %}

	<h1 class="text-center">No current investments!</h1>

		<form  action="" method="GET">
	 	<input id="stock_ticker" name="stock_ticker" type="text" placeholder="Search ticker...">
		</form>

	{% endif %}

{% endblock %}